"""change meal table: add one field

Revision ID: d5186b4c14ec
Revises: fc5f47fe1710
Create Date: 2025-05-27 11:26:20.176703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5186b4c14ec'
down_revision: Union[str, None] = 'fc5f47fe1710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal', sa.Column('added_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'meal', 'user', ['added_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meal', type_='foreignkey')
    op.drop_column('meal', 'added_by')
    # ### end Alembic commands ###
